// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID        int32
	UserID    int32
	KeyValue  string
	IsActive  pgtype.Bool
	CreatedAt pgtype.Timestamptz
}

type UsageLog struct {
	ID               int32
	ApiKeyID         int32
	Provider         string
	Model            string
	PromptTokens     pgtype.Int4
	CompletionTokens pgtype.Int4
	TotalTokens      pgtype.Int4
	LatencyMs        pgtype.Int4
	StatusCode       pgtype.Int4
	CreatedAt        pgtype.Timestamptz
}

type User struct {
	ID        int32
	Username  string
	CreatedAt pgtype.Timestamptz
}
