// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, key_value) 
VALUES ($1, $2) 
RETURNING id, user_id, key_value, is_active, created_at
`

type CreateAPIKeyParams struct {
	UserID   int32
	KeyValue string
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey, arg.UserID, arg.KeyValue)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyValue,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createUsageLog = `-- name: CreateUsageLog :exec
INSERT INTO usage_logs (
    api_key_id, provider, model, prompt_tokens,
    completion_tokens, total_tokens, latency_ms, status_code
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type CreateUsageLogParams struct {
	ApiKeyID         int32
	Provider         string
	Model            string
	PromptTokens     pgtype.Int4
	CompletionTokens pgtype.Int4
	TotalTokens      pgtype.Int4
	LatencyMs        pgtype.Int4
	StatusCode       pgtype.Int4
}

func (q *Queries) CreateUsageLog(ctx context.Context, arg CreateUsageLogParams) error {
	_, err := q.db.Exec(ctx, createUsageLog,
		arg.ApiKeyID,
		arg.Provider,
		arg.Model,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
		arg.LatencyMs,
		arg.StatusCode,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username) 
VALUES ($1) 
RETURNING id, username, created_at
`

func (q *Queries) CreateUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, username)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.CreatedAt)
	return i, err
}

const getUserByAPIKey = `-- name: GetUserByAPIKey :one
SELECT u.id, u.username, u.created_at FROM users u
JOIN api_keys ak ON u.id = ak.user_id
WHERE ak.key_value = $1 AND ak.is_active = true
`

func (q *Queries) GetUserByAPIKey(ctx context.Context, keyValue string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAPIKey, keyValue)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.CreatedAt)
	return i, err
}
