// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID        int32
	UserID    int32
	KeyValue  string
	IsActive  pgtype.Bool
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID        int32
	Username  string
	CreatedAt pgtype.Timestamptz
}
