// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, key_value) VALUES ($1, $2) RETURNING id, user_id, key_value, is_active, created_at
`

type CreateAPIKeyParams struct {
	UserID   int32
	KeyValue string
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey, arg.UserID, arg.KeyValue)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyValue,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username) VALUES ($1) RETURNING id, username, created_at
`

func (q *Queries) CreateUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, username)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.CreatedAt)
	return i, err
}

const getUserByAPIKey = `-- name: GetUserByAPIKey :one
SELECT u.id, u.username, u.created_at FROM users u
JOIN api_keys ak ON u.id = ak.user_id
WHERE ak.key_value = $1 AND ak.is_active = true
`

func (q *Queries) GetUserByAPIKey(ctx context.Context, keyValue string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAPIKey, keyValue)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.CreatedAt)
	return i, err
}
